import {chromium} from 'playwright';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';import {startStaticPreview} from './static-preview.mjs';
const dir='review-output/review-5263461859';await mkdir(dir,{recursive:true});const server=await startStaticPreview(),browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--use-angle=swiftshader']});const report={checks:[],errors:[],samples:{}};const check=(name,ok,data)=>{report.checks.push({name,pass:!!ok,data});if(!ok)report.errors.push(name);};
try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir,size:{width:1440,height:1000}}}),page=await ctx.newPage();page.setDefaultTimeout(30000);page.on('pageerror',e=>report.errors.push(e.message));
 await page.goto(server.base+'/?scenePerf=1',{waitUntil:'networkidle'});await page.waitForFunction(()=>!!document.querySelector('particle-field')?.particleSnapshot);const dust=page.locator('particle-field').first(),snapshot=()=>dust.evaluate(e=>e.particleSnapshot());const b=await dust.boundingBox();const initial=await snapshot();
 await page.mouse.move(b.x+180,b.y+b.height*.62);for(let n=1;n<=30;n++){await page.mouse.move(b.x+180+n*32,b.y+b.height*.62+35*Math.sin(n/30*Math.PI*4));await page.waitForTimeout(1000/30);}const swept=await snapshot();await page.waitForTimeout(250);const after=await snapshot();const active=swept.particles.filter(p=>Math.hypot(p.vx,p.vy)>80);const moves=active.map(p=>Math.hypot(after.particles[p.id].x-p.x,after.particles[p.id].y-p.y));check('home strong samples move tens of pixels in .25s',moves.length>10&&moves.reduce((a,b)=>a+b,0)/moves.length>15,{count:moves.length,mean:moves.reduce((a,b)=>a+b,0)/moves.length});
 await page.waitForTimeout(1800);const rest=await snapshot();check('stationary pointer impulse decays',Math.max(...rest.particles.map(p=>Math.hypot(p.vx,p.vy)))<40);report.samples.home={before:initial.particles.filter((_,i)=>i%80===0),swept:swept.particles.filter((_,i)=>i%80===0),after:after.particles.filter((_,i)=>i%80===0)};await page.screenshot({path:dir+'/home-flow.png'});
 await page.goto(server.base+'/playground/?scenePerf=1',{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('[data-inline-spark]')?.dataset.sparkState==='ready');const spark=page.locator('[data-inline-spark]'),host=spark.locator('[data-particle-host]');const seek=async p=>{await spark.evaluate((e,p)=>scrollTo({top:Number(e.dataset.scrollStart)+(Number(e.dataset.scrollEnd)-Number(e.dataset.scrollStart))*p,behavior:'instant'}),p);await page.waitForFunction(p=>Math.abs(document.querySelector('[data-particle-host]').particleSnapshot().progress-p)<.001,p);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));return host.evaluate(e=>e.particleSnapshot());};
 const a=await seek(.3),c=await seek(.45);const moving=c.particles.filter((p,i)=>p.alpha>.01&&Math.hypot(p.x-a.particles[i].x,p.y-a.particles[i].y)>.1).length,visible=c.particles.filter(p=>p.alpha>.01).length;check('all visible Spark groups move at .30 to .45',moving===visible&&visible>100,{moving,visible});await page.screenshot({path:dir+'/spark-guided.png'});await seek(.95);const back=await seek(.45);const seekError=Math.max(...back.particles.map((p,i)=>Math.hypot(p.x-c.particles[i].x,p.y-c.particles[i].y)));check('actual browser reverse seek matches positions',seekError<.01,{forward:c.progress,reverse:back.progress,maxPositionDifference:seekError});const late=await seek(.95);check('Spark absorbs every particle',late.particles.every(p=>p.alpha===0));await seek(.45);
 const draws=await host.evaluate(async e=>{const before=e.particleSnapshot().renderCount;for(let i=0;i<100;i++)e.setScene({progress:.45});const immediate=e.particleSnapshot().renderCount;await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {before,immediate,after:e.particleSnapshot().renderCount};});check('100 scene callbacks do not draw',draws.immediate===draws.before,draws);check('one particle draw per RAF',draws.after-draws.before<=2,draws);report.samples.spark={at30:a.particles.filter((_,i)=>i%80===0),at45:c.particles.filter((_,i)=>i%80===0)};
 await page.setViewportSize({width:1280,height:640});await page.goto(server.base+'/projects/threadcove/?scenePerf=1',{waitUntil:'networkidle'});const cloth=page.locator('[data-paper-cloth]');await cloth.scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('[data-paper-cloth]')?.dataset.clothState==='running');check('short desktop fits',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:dir+'/cove-short-desktop.png'});
 const contextExtension=await cloth.locator('canvas').evaluate(e=>{const gl=e.getContext('webgl2'),ext=gl?.getExtension('WEBGL_lose_context');window.__lost=ext;ext?.loseContext();return !!ext;});check('context loss exercised',contextExtension);await page.waitForFunction(()=>document.querySelector('[data-paper-cloth]')?.dataset.clothState==='fallback');await page.waitForTimeout(150);await page.evaluate(()=>window.__lost.restoreContext());await page.waitForFunction(()=>document.querySelector('[data-paper-cloth]')?.dataset.clothState==='running');check('cloth context restores one canvas',await cloth.locator('canvas').count()===1);
 await page.evaluate(()=>scrollTo({top:document.body.scrollHeight,behavior:'instant'}));await page.waitForTimeout(150);check('offscreen cloth stops',await cloth.getAttribute('data-cloth-state')==='paused');await ctx.close();
 const fallback=await browser.newContext({viewport:{width:1280,height:640}});await fallback.route('**/baked-poses*.js',route=>route.fulfill({contentType:'application/javascript',body:'export default {};'}));const f=await fallback.newPage();f.setDefaultTimeout(30000);await f.addInitScript(()=>{window.__heartbeat=0;setInterval(()=>window.__heartbeat++,10);});await f.goto(server.base+'/?scenePerf=1',{waitUntil:'networkidle'});await f.locator('#cloth-stage').scrollIntoViewIfNeeded();await f.waitForFunction(()=>document.querySelector('#cloth-stage')?.dataset.clothState==='running');check('missing bake uses yielding preparation',await f.evaluate(()=>window.__heartbeat>10));await fallback.close();
} catch(e){report.errors.push(String(e));}finally{await writeFile(dir+'/browser-regression.json',JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify({checks:report.checks,errors:report.errors},null,2));assert.equal(report.errors.length,0,report.errors.join('\n'));
