import {readFile,writeFile} from 'node:fs/promises';
const dir='review-output/review-5263461859',load=async name=>JSON.parse(await readFile(dir+'/'+name+'.json','utf8')),median=a=>{a=a.filter(Number.isFinite).sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:null;};
const before=await load('browser-before');try{const supplemental=await load('browser-before-spark');before.rows=[...before.rows.filter(r=>r.name!=='spark'),...supplemental.rows];}catch{}const after=await load('browser-after'),cpuBefore=await load('solver-before'),cpuAfter=await load('solver-after');
const f=n=>n===null?'n/a':n.toFixed(1),summary={cpu:[],browser:[]};
for(const name of ['home','cove']){const a=cpuBefore.rows.filter(r=>r.name===name),b=cpuAfter.rows.filter(r=>r.name===name);summary.cpu.push({name,constructorBefore:median(a.map(r=>r.constructionMs)),constructorAfter:median(b.map(r=>r.constructionMs)),stepP50Before:median(a.map(r=>r.stepP50)),stepP50After:median(b.map(r=>r.stepP50)),stepP95Before:median(a.map(r=>r.stepP95)),stepP95After:median(b.map(r=>r.stepP95))});}
for(const name of ['home','cove','claw','spark'])for(const cache of ['cold','warm']){const a=before.rows.filter(r=>r.name===name&&r.cache===cache),b=after.rows.filter(r=>r.name===name&&r.cache===cache);summary.browser.push({name,cache,firstDrawBefore:median(a.map(r=>r.draws[name])),firstDrawAfter:median(b.map(r=>r.draws[name]??r.readiness?.['spark-particles']?.stamps['first-render'])),readyBefore:median(a.map(r=>r.preparedToInteractive)),readyAfter:median(b.map(r=>r.preparedToInteractive)),p50Before:median(a.map(r=>r.p50)),p50After:median(b.map(r=>r.p50)),p95Before:median(a.map(r=>r.p95)),p95After:median(b.map(r=>r.p95)),longBefore:median(a.map(r=>r.long.reduce((s,e)=>s+e.duration,0))),longAfter:median(b.map(r=>r.long.reduce((s,e)=>s+e.duration,0))),transferBefore:median(a.map(r=>r.resources.reduce((s,e)=>s+e.transferSize,0))),transferAfter:median(b.map(r=>r.resources.reduce((s,e)=>s+e.transferSize,0)))});}
let text='\n### 同机 CPU 中位数（ms）\n\n| 场景 | 构造前→后 | 每 120Hz 步 p50 前→后 | 每步 p95 前→后 |\n|---|---:|---:|---:|\n';for(const r of summary.cpu)text+='| '+r.name+' | '+f(r.constructorBefore)+' → '+f(r.constructorAfter)+' | '+f(r.stepP50Before)+' → '+f(r.stepP50After)+' | '+f(r.stepP95Before)+' → '+f(r.stepP95After)+' |\n';
text+='\n### 浏览器三次中位数（ms）\n\n“滚入后就绪”为发起 scrollIntoView 至自动化观察 ready/running 的时间，含滚动和轮询开销；不是纯初始化耗时。首绘为导航后主 framebuffer 的首次 WebGL 提交，after 为完整准备后首次提交。旧版可能先提交未完成环境/文字的中间状态。Spark 的旧版 Canvas 首绘来自相同条件的补充六次采集 browser-before-spark.json。\n\n| 场景/导航 | 首绘 前→后 | 滚入后就绪 前→后 | 帧间隔 p50 前→后 | 帧间隔 p95 前→后 | 长任务总时长 前→后 |\n|---|---:|---:|---:|---:|---:|\n';for(const r of summary.browser)text+='| '+r.name+'/'+r.cache+' | '+f(r.firstDrawBefore)+' → '+f(r.firstDrawAfter)+' | '+f(r.readyBefore)+' → '+f(r.readyAfter)+' | '+f(r.p50Before)+' → '+f(r.p50After)+' | '+f(r.p95Before)+' → '+f(r.p95After)+' | '+f(r.longBefore)+' → '+f(r.longAfter)+' |\n';
text+='\n| 场景/导航 | 资源 transferSize 前→后（字节） |\n|---|---:|\n';for(const r of summary.browser)text+='| '+r.name+'/'+r.cache+' | '+r.transferBefore+' → '+r.transferAfter+' |\n';await writeFile(dir+'/summary.json',JSON.stringify(summary,null,2));await writeFile(dir+'/performance-table.md',text);console.log(JSON.stringify(summary));
